apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
        name: configmap-role
rules:
       - apiGroups: [""]
         resources: ["pods","pods/log","configmaps"]
         verbs: ["get", "list", "watch"]
---
          
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
        name: read-configmaps-rolebinding
        namespace: springkube-ns
subjects:
        - kind: ServiceAccount
          name: springkube-sa
          namespace: springkube-ns 
roleRef:
  kind: Role
  name: configmap-role  
  apiGroup: rbac.authorization.k8s.io
