apiVersion: v1
kind: Service
metadata:
        name: springkubedemo-svc
        labels:
                app: springkubedemo
spec:
        type: NodePort
        ports:
                - port: 8080
                  targetPort: 8080
                  nodePort: 30663
                  protocol: TCP
        selector:
                app: springkubedemo
